main: main.c player.c player.h  menu.c menu.h   assets.h structs.h game_gui.c game_gui.h levels.c levels.h map.h map.c image.c image.h enigme.c enigme.h enemy.c enemy.h
	gcc main.c player.c  menu.c game_gui.c map.c enemy.c levels.c image.c enigme.c -lSDL -lSDL_ttf -lSDL_mixer -lSDL_image -lSDL_gfx -lm -g -o game

clean:
	rm main
